title: ander9991's blog
author: ander9991
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A simple blogpost.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ander9991 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
